/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Component;
import java.awt.Dimension;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableModel;
import structures.Import;
import structures.Preproc;
import structures.Project;

/**
 *
 * @author alba
 */
public class JPImport extends javax.swing.JPanel {
    
    public JPImport(JTPMain ctrl) 
    {
        initComponents();
        controller = ctrl;
        
        initChannelsTable();
        initComboBoxSystem();
        initComboRefChannels();
        //initGUI(project);

    }
    
    public void initGUI(Project init_proj)
    {
        initChannelsTable();
        initComboBoxSystem();
        initComboRefChannels();
    }
    
    public void setGUI(Project proj)
    {
        project = proj;
        imp = project.imp;
    }
    
    public Project getGUI(Project proj)
    {
        proj.imp.acquisition_system = (String) jComboBox_acquisition_system.getSelectedItem();
        
        proj.imp.original_data_extension = jTextField_DataExtension.getText();
        proj.imp.original_data_folder = jTextField_DataFolder.getText();
        proj.imp.original_data_suffix = jTextField_NameSuffix.getText();
        proj.imp.original_data_prefix = jTextField_NamePrefix.getText();
        proj.imp.output_folder = jTextField_OutputDataFolder.getText();
        proj.imp.output_suffix = jTextField_OutputNameSuffix.getText();
        
        for (int i = 0; i < jTableDM_ChannelsTransf.getRowCount(); i++) 
        {
            proj.imp.ch2transform[i].new_label  = (String) jTable_ChannelsTransf.getModel().getValueAt(i,0);
            proj.imp.ch2transform[i].type       = (String) jTable_ChannelsTransf.getModel().getValueAt(i,1);
            proj.imp.ch2transform[i].ch1[0]     = Double.parseDouble((String) jTable_ChannelsTransf.getModel().getValueAt(i,2));
            proj.imp.ch2transform[i].ch2[0]     = Double.parseDouble((String) jTable_ChannelsTransf.getModel().getValueAt(i,3));
        }
        
        if (jComboBox_RefChannels.getSelectedItem() == "other")
        {proj.imp.reference_channels[0] = jTextField_RefChannel.getText();}
        else if (jComboBox_RefChannels.getSelectedItem() == "none")
        {proj.imp.reference_channels[0] = "";}
        else
        {proj.imp.reference_channels[0] = (String) jComboBox_RefChannels.getSelectedItem();}
        
        // valid_marker ??
        
        // ignore emg_output_postfix 
        
        return proj;
    }
 
    /*
    String acquisition_system = jTextField_System.getText();
        System.out.println(acquisition_system);
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPimport_data = new javax.swing.JPanel();
        jLabel_System = new javax.swing.JLabel();
        jLabel_DataExtension = new javax.swing.JLabel();
        jLabel_DataFolder = new javax.swing.JLabel();
        jLabel_OriginalDataInfo = new javax.swing.JLabel();
        jTextField_DataFolder = new javax.swing.JTextField();
        jLabel_NamePrefix = new javax.swing.JLabel();
        jTextField_NamePrefix = new javax.swing.JTextField();
        jLabel_NameSuffix = new javax.swing.JLabel();
        jTextField_NameSuffix = new javax.swing.JTextField();
        jLabel_ExampleS01 = new javax.swing.JLabel();
        jTextField_InputExample = new javax.swing.JTextField();
        jLabel_OutputDataInfo = new javax.swing.JLabel();
        jLabel_DataFolderOutput = new javax.swing.JLabel();
        jLabel_NameSuffixOutput = new javax.swing.JLabel();
        jLabel_InputExample = new javax.swing.JLabel();
        jTextField_OutputNameSuffix = new javax.swing.JTextField();
        jButton_ChannelsTransfClear = new javax.swing.JButton();
        jButton_ChannelsTransfRemove = new javax.swing.JButton();
        jLabel_ChannelsTransf = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_ChannelsTransf = new javax.swing.JTable();
        jTextField_OutputDataFolder = new javax.swing.JTextField();
        jTextField_DataExtension = new javax.swing.JTextField();
        jLabel_RefChannels = new javax.swing.JLabel();
        jTextField_RefChannel = new javax.swing.JTextField();
        jComboBox_acquisition_system = new javax.swing.JComboBox();
        jTextField_fs = new javax.swing.JTextField();
        jLabel_ChannelsFileName = new javax.swing.JLabel();
        jTextField_ChannelsFileName = new javax.swing.JTextField();
        jLabel_FinalChannels = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_FinalChannels = new javax.swing.JTable();
        jLabel_TotChannels = new javax.swing.JLabel();
        jTextField_TotChannels = new javax.swing.JTextField();
        jLabel_ChannelsFileName1 = new javax.swing.JLabel();
        jLabel_EEGChannels = new javax.swing.JLabel();
        jTextField_ChannelsFilePath = new javax.swing.JTextField();
        jTextField_EEGChannels = new javax.swing.JTextField();
        jButton_channels_file_path_select = new javax.swing.JButton();
        jLabel_fs = new javax.swing.JLabel();
        jComboBox_RefChannels = new javax.swing.JComboBox();
        jLabel_OutputExample = new javax.swing.JLabel();
        jTextField_OutputExample = new javax.swing.JTextField();
        jButton_ChannelsTransfApply = new javax.swing.JButton();
        jButton_ChannelsTransfNew = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1150, 750));

        jPimport_data.setName("import_data"); // NOI18N
        jPimport_data.setPreferredSize(new java.awt.Dimension(1150, 750));

        jLabel_System.setText("system");

        jLabel_DataExtension.setText("data extension");

        jLabel_DataFolder.setText("data folder");

        jLabel_OriginalDataInfo.setText("ORIGINAL DATA INFO");

        jTextField_DataFolder.setName("original_data_folder"); // NOI18N

        jLabel_NamePrefix.setText("name prefix");

        jTextField_NamePrefix.setName("original_data_prefix"); // NOI18N

        jLabel_NameSuffix.setText("name suffix");

        jTextField_NameSuffix.setName("original_data_suffix"); // NOI18N

        jLabel_ExampleS01.setText("example S_01");

        jTextField_InputExample.setEnabled(false);
        jTextField_InputExample.setName("input_example_name"); // NOI18N

        jLabel_OutputDataInfo.setText("OUTPUT DATA INFO");

        jLabel_DataFolderOutput.setText("data folder");

        jLabel_NameSuffixOutput.setText("output suffix");
        jLabel_NameSuffixOutput.setToolTipText("");

        jLabel_InputExample.setText("INPUT");

        jTextField_OutputNameSuffix.setName("output_suffix"); // NOI18N
        jTextField_OutputNameSuffix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_OutputNameSuffixKeyTyped(evt);
            }
        });

        jButton_ChannelsTransfClear.setText("clear");
        jButton_ChannelsTransfClear.setName("ch2transform_btNew"); // NOI18N
        jButton_ChannelsTransfClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChannelsTransfClearActionPerformed(evt);
            }
        });

        jButton_ChannelsTransfRemove.setText("remove");
        jButton_ChannelsTransfRemove.setName("ch2transform_btRemove"); // NOI18N
        jButton_ChannelsTransfRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChannelsTransfRemoveActionPerformed(evt);
            }
        });

        jLabel_ChannelsTransf.setText("Channels Transformation");

        jTable_ChannelsTransf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_ChannelsTransf.setName("ch2transform"); // NOI18N
        jTable_ChannelsTransf.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable_ChannelsTransf);

        jTextField_OutputDataFolder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_OutputDataFolderKeyTyped(evt);
            }
        });

        jTextField_DataExtension.setEditable(false);
        jTextField_DataExtension.setText("jTextField1");
        jTextField_DataExtension.setEnabled(false);

        jLabel_RefChannels.setText("Reference Channel");

        jTextField_RefChannel.setText("jTextField1");
        jTextField_RefChannel.setEnabled(false);

        jComboBox_acquisition_system.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox_acquisition_systemFocusLost(evt);
            }
        });

        jTextField_fs.setName("fs"); // NOI18N

        jLabel_ChannelsFileName.setText("channels file name");

        jTextField_ChannelsFileName.setName("eeglab_channels_file_name"); // NOI18N

        jLabel_FinalChannels.setText("Final Channels ");

        jTable_FinalChannels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Id", "Label", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_FinalChannels.setColumnSelectionAllowed(true);
        jTable_FinalChannels.setName("final_channels_list"); // NOI18N
        jTable_FinalChannels.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_FinalChannels);

        jLabel_TotChannels.setText("tot channels");

        jTextField_TotChannels.setName("nch"); // NOI18N

        jLabel_ChannelsFileName1.setText("channels file path");

        jLabel_EEGChannels.setText("eeg channels");

        jTextField_ChannelsFilePath.setEnabled(false);
        jTextField_ChannelsFilePath.setName("eeglab_channels_file_name"); // NOI18N

        jTextField_EEGChannels.setEditable(false);
        jTextField_EEGChannels.setEnabled(false);
        jTextField_EEGChannels.setName("nch_eeg"); // NOI18N

        jButton_channels_file_path_select.setText("Select");
        jButton_channels_file_path_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_channels_file_path_selectActionPerformed(evt);
            }
        });

        jLabel_fs.setText("fs");

        jComboBox_RefChannels.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox_RefChannelsFocusLost(evt);
            }
        });

        jLabel_OutputExample.setText("OUTPUT");

        jTextField_OutputExample.setEnabled(false);
        jTextField_OutputExample.setName("input_example_name"); // NOI18N

        jButton_ChannelsTransfApply.setText("apply");
        jButton_ChannelsTransfApply.setName("ch2transform_btNew"); // NOI18N
        jButton_ChannelsTransfApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChannelsTransfApplyActionPerformed(evt);
            }
        });

        jButton_ChannelsTransfNew.setText("new");
        jButton_ChannelsTransfNew.setName("ch2transform_btNew"); // NOI18N
        jButton_ChannelsTransfNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChannelsTransfNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPimport_dataLayout = new javax.swing.GroupLayout(jPimport_data);
        jPimport_data.setLayout(jPimport_dataLayout);
        jPimport_dataLayout.setHorizontalGroup(
            jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPimport_dataLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel_ExampleS01, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_InputExample, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_OutputExample, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_OutputExample, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_InputExample, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPimport_dataLayout.createSequentialGroup()
                    .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPimport_dataLayout.createSequentialGroup()
                            .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPimport_dataLayout.createSequentialGroup()
                                    .addGap(590, 590, 590)
                                    .addComponent(jLabel_ChannelsFileName1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPimport_dataLayout.createSequentialGroup()
                                    .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPimport_dataLayout.createSequentialGroup()
                                            .addComponent(jLabel_RefChannels)
                                            .addGap(28, 28, 28)
                                            .addComponent(jComboBox_RefChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField_RefChannel))
                                        .addGroup(jPimport_dataLayout.createSequentialGroup()
                                            .addComponent(jLabel_TotChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_TotChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel_EEGChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_EEGChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(jLabel_fs, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField_fs, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_ChannelsFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                        .addGroup(jPimport_dataLayout.createSequentialGroup()
                            .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPimport_dataLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel_FinalChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPimport_dataLayout.createSequentialGroup()
                                    .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPimport_dataLayout.createSequentialGroup()
                                            .addComponent(jLabel_ChannelsTransf, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton_ChannelsTransfNew, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton_ChannelsTransfRemove)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton_ChannelsTransfApply, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton_ChannelsTransfClear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(42, 42, 42)))
                    .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPimport_dataLayout.createSequentialGroup()
                            .addComponent(jTextField_ChannelsFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_channels_file_path_select))
                        .addComponent(jTextField_ChannelsFileName, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGap(1001, 1001, 1001)))
            .addGroup(jPimport_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_OriginalDataInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_OutputDataInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_System, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_DataFolderOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_OutputDataFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jComboBox_acquisition_system, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_DataExtension, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jLabel_NameSuffixOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_OutputNameSuffix, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jTextField_DataExtension))
                .addGap(54, 54, 54)
                .addComponent(jLabel_DataFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_DataFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel_NamePrefix, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_NamePrefix, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel_NameSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_NameSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPimport_dataLayout.setVerticalGroup(
            jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPimport_dataLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_OriginalDataInfo)
                    .addComponent(jLabel_System)
                    .addComponent(jLabel_DataExtension)
                    .addComponent(jLabel_DataFolder)
                    .addComponent(jTextField_DataFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_NamePrefix)
                    .addComponent(jTextField_NamePrefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_NameSuffix)
                    .addComponent(jTextField_NameSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_DataExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_acquisition_system, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_OutputDataInfo)
                    .addComponent(jLabel_DataFolderOutput)
                    .addComponent(jLabel_NameSuffixOutput)
                    .addComponent(jTextField_OutputNameSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_OutputDataFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ExampleS01)
                    .addComponent(jTextField_InputExample, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_InputExample))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_OutputExample)
                    .addComponent(jTextField_OutputExample, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TotChannels)
                    .addComponent(jTextField_TotChannels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_EEGChannels)
                    .addComponent(jTextField_EEGChannels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_fs)
                    .addComponent(jTextField_fs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ChannelsFileName)
                    .addComponent(jTextField_ChannelsFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ChannelsFileName1)
                    .addComponent(jTextField_ChannelsFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_channels_file_path_select))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_FinalChannels))
                    .addGroup(jPimport_dataLayout.createSequentialGroup()
                        .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_RefChannels)
                            .addComponent(jComboBox_RefChannels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_RefChannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPimport_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_ChannelsTransfClear)
                            .addComponent(jLabel_ChannelsTransf)
                            .addComponent(jButton_ChannelsTransfRemove)
                            .addComponent(jButton_ChannelsTransfApply)
                            .addComponent(jButton_ChannelsTransfNew))
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );

        jLabel_RefChannels.getAccessibleContext().setAccessibleName("Reference Channels");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPimport_data, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPimport_data, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_OutputNameSuffixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_OutputNameSuffixKeyTyped
        String text = jTextField_OutputDataFolder.getText()+jTextField_OutputNameSuffix.getText();
        jTextField_OutputExample.setText(text);
    }//GEN-LAST:event_jTextField_OutputNameSuffixKeyTyped

    private void jButton_ChannelsTransfRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChannelsTransfRemoveActionPerformed
        jTableDM_ChannelsTransf.removeRow(jTable_ChannelsTransf.getSelectedRow());
    }//GEN-LAST:event_jButton_ChannelsTransfRemoveActionPerformed

    private void jButton_ChannelsTransfClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChannelsTransfClearActionPerformed
        initChannelsTable(); 
    }//GEN-LAST:event_jButton_ChannelsTransfClearActionPerformed

    private void jComboBox_acquisition_systemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox_acquisition_systemFocusLost
        if (jComboBox_acquisition_system.getSelectedItem() == "Biosemi")
        //if (jComboBox_acquisition_system.getSelectedIndex() == 1)
        {jTextField_DataExtension.setText(".bdf");}
        else if (jComboBox_acquisition_system.getSelectedItem() == "BrainVision")
        {jTextField_DataExtension.setText(".vhdr");}
    }//GEN-LAST:event_jComboBox_acquisition_systemFocusLost

    private void jComboBox_RefChannelsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox_RefChannelsFocusLost
        if (jComboBox_RefChannels.getSelectedItem() == "other")
        {
            jTextField_RefChannel.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox_RefChannelsFocusLost

    private void jTextField_OutputDataFolderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_OutputDataFolderKeyTyped
        String text = jTextField_OutputDataFolder.getText()+jTextField_OutputNameSuffix.getText();
        jTextField_OutputExample.setText(text);
    }//GEN-LAST:event_jTextField_OutputDataFolderKeyTyped

    private void jButton_channels_file_path_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_channels_file_path_selectActionPerformed
        JFileChooser fc = new JFileChooser(); 
        fc.showOpenDialog(null);
        String path = fc.getSelectedFile().getAbsolutePath();
        jTextField_ChannelsFilePath.setText(path);
    }//GEN-LAST:event_jButton_channels_file_path_selectActionPerformed

    private void jButton_ChannelsTransfApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChannelsTransfApplyActionPerformed
        initFinalChannelsTable();
    }//GEN-LAST:event_jButton_ChannelsTransfApplyActionPerformed

    private void jButton_ChannelsTransfNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChannelsTransfNewActionPerformed
        Object[] obj=null;
        jTableDM_ChannelsTransf.addRow(obj);
        jTable_ChannelsTransf.setModel(jTableDM_ChannelsTransf);
    }//GEN-LAST:event_jButton_ChannelsTransfNewActionPerformed

    private void initChannelsTable()
    {
        Object[] columnName = {"new_label","type","ch1","ch2",};          
        jTableDM_ChannelsTransf = new DefaultTableModel(columnName, 0);
        jTable_ChannelsTransf.setModel(jTableDM_ChannelsTransf);        
        
        Object[] cmbinitvalues = {"eeg", "emg", "eog", "others"};
        JComboBox comboBox = new JComboBox(cmbinitvalues);
        comboBox.setMaximumRowCount(4);
        TableCellEditor editor = new DefaultCellEditor(comboBox);        
        jTable_ChannelsTransf.getColumnModel().getColumn(1).setCellEditor(editor);
    }
    
    private void initFinalChannelsTable()
    {
        Object[] columnName = {"Id","Label","Type"};        
        int nch = (int) Double.parseDouble(jTextField_TotChannels.getText());
        int l_ch2transf = jTable_ChannelsTransf.getRowCount();
        jTableDM_FinalChannels = new DefaultTableModel(columnName, nch+l_ch2transf);   
        jTable_FinalChannels.setModel(jTableDM_FinalChannels);
        
        for (int i = 0; i < (nch+l_ch2transf); i++) 
        {
            jTable_FinalChannels.setValueAt(String.valueOf(i), i, 0);
            if (i < nch)
            {
                jTable_FinalChannels.setValueAt(String.valueOf(i), i, 1);
                jTable_FinalChannels.setValueAt("eeg", i, 2);
            }  
            else
            {
                String label_ch = (String) jTable_ChannelsTransf.getValueAt(i-nch, 0);
                String type_ch = (String) jTable_ChannelsTransf.getValueAt(i-nch, 1); 
                jTable_FinalChannels.setValueAt(label_ch, i, 1);
                jTable_FinalChannels.setValueAt(type_ch, i, 2);
            }
        }
 
    }
    
    private void initComboBoxSystem()
    {
        jComboBox_acquisition_system.addItem("Biosemi");
        jComboBox_acquisition_system.addItem("BrainVision");
    }
    
    private void initComboRefChannels()
    {
        //  ref channel :  "CAR", empty, "other"  -> enable text field....
        jComboBox_RefChannels.addItem("CAR");
        jComboBox_RefChannels.addItem("none");
        jComboBox_RefChannels.addItem("other");
    }
    

    private Import imp;
    private Project project;
    private JTPMain controller;
    DefaultTableModel jTableDM_ChannelsTransf;
    DefaultTableModel jTableDM_FinalChannels;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ChannelsTransfApply;
    private javax.swing.JButton jButton_ChannelsTransfClear;
    private javax.swing.JButton jButton_ChannelsTransfNew;
    private javax.swing.JButton jButton_ChannelsTransfRemove;
    private javax.swing.JButton jButton_channels_file_path_select;
    private javax.swing.JComboBox jComboBox_RefChannels;
    private javax.swing.JComboBox jComboBox_acquisition_system;
    private javax.swing.JLabel jLabel_ChannelsFileName;
    private javax.swing.JLabel jLabel_ChannelsFileName1;
    private javax.swing.JLabel jLabel_ChannelsTransf;
    private javax.swing.JLabel jLabel_DataExtension;
    private javax.swing.JLabel jLabel_DataFolder;
    private javax.swing.JLabel jLabel_DataFolderOutput;
    private javax.swing.JLabel jLabel_EEGChannels;
    private javax.swing.JLabel jLabel_ExampleS01;
    private javax.swing.JLabel jLabel_FinalChannels;
    private javax.swing.JLabel jLabel_InputExample;
    private javax.swing.JLabel jLabel_NamePrefix;
    private javax.swing.JLabel jLabel_NameSuffix;
    private javax.swing.JLabel jLabel_NameSuffixOutput;
    private javax.swing.JLabel jLabel_OriginalDataInfo;
    private javax.swing.JLabel jLabel_OutputDataInfo;
    private javax.swing.JLabel jLabel_OutputExample;
    private javax.swing.JLabel jLabel_RefChannels;
    private javax.swing.JLabel jLabel_System;
    private javax.swing.JLabel jLabel_TotChannels;
    private javax.swing.JLabel jLabel_fs;
    private javax.swing.JPanel jPimport_data;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_ChannelsTransf;
    private javax.swing.JTable jTable_FinalChannels;
    private javax.swing.JTextField jTextField_ChannelsFileName;
    private javax.swing.JTextField jTextField_ChannelsFilePath;
    private javax.swing.JTextField jTextField_DataExtension;
    private javax.swing.JTextField jTextField_DataFolder;
    private javax.swing.JTextField jTextField_EEGChannels;
    private javax.swing.JTextField jTextField_InputExample;
    private javax.swing.JTextField jTextField_NamePrefix;
    private javax.swing.JTextField jTextField_NameSuffix;
    private javax.swing.JTextField jTextField_OutputDataFolder;
    private javax.swing.JTextField jTextField_OutputExample;
    private javax.swing.JTextField jTextField_OutputNameSuffix;
    private javax.swing.JTextField jTextField_RefChannel;
    private javax.swing.JTextField jTextField_TotChannels;
    private javax.swing.JTextField jTextField_fs;
    // End of variables declaration//GEN-END:variables
}
