/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import structures.Epoching;
import structures.Erp;
import structures.Project;

/**
 *
 * @author inuggi
 */
public class JPOperations extends javax.swing.JPanel {

    private JTPMain controller;
    public Erp erp;
    public Project project;
    
    public JPOperations(JTPMain ctrl) {
        initComponents();
        
        initAnalysisTable();
        initGpeSubjectButtons();
        
        controller = ctrl;
    }

    
    public void setGUI(Project proj)
    {
        project = proj;
        erp = project.erp;
    }
    
    public Project getGUI(Project proj)
    {
        // I don't know how to do ? Erp or Ersp ...
        
        
        return proj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Analysis = new javax.swing.JTable();
        jLabel_AnalysisName = new javax.swing.JLabel();
        jLabel_ConditionFolder = new javax.swing.JLabel();
        jRadioButton_Subject = new javax.swing.JRadioButton();
        jRadioButton_Group = new javax.swing.JRadioButton();
        jButton_Start = new javax.swing.JButton();
        jTextField_ConditionFolder = new javax.swing.JTextField();
        jTextField_AnalysisName = new javax.swing.JTextField();
        jLabel_Analysis = new javax.swing.JLabel();

        jTable_Analysis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Analysis", "Execute"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Analysis);

        jLabel_AnalysisName.setText("Analysis name");

        jLabel_ConditionFolder.setText("Condition folder");

        jRadioButton_Subject.setText("Subject");

        jRadioButton_Group.setText("Group");

        jButton_Start.setText("Start");
        jButton_Start.setName("$Start"); // NOI18N
        jButton_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StartActionPerformed(evt);
            }
        });

        jTextField_ConditionFolder.setText("jTextField1");

        jTextField_AnalysisName.setText("jTextField1");

        jLabel_Analysis.setText("Analysis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_AnalysisName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_AnalysisName, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_ConditionFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_ConditionFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton_Subject)
                                    .addComponent(jRadioButton_Group)))
                            .addComponent(jLabel_Analysis, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(224, 224, 224)
                        .addComponent(jButton_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_ConditionFolder)
                            .addComponent(jTextField_ConditionFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_AnalysisName)
                            .addComponent(jTextField_AnalysisName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Start)
                            .addComponent(jLabel_Analysis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton_Subject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton_Group)
                        .addGap(18, 18, 18))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StartActionPerformed
        
    }//GEN-LAST:event_jButton_StartActionPerformed

    private void initAnalysisTable()
    {
        Object[] columnName = {"Analysis","Execute"};          
        jTableDM_Analysis = new DefaultTableModel(columnName, 1);
        jTable_Analysis.setModel(jTableDM_Analysis);  
        
        JCheckBox checkBox = new JCheckBox();
        TableCellEditor editor = new DefaultCellEditor(checkBox);        
        jTable_Analysis.getColumnModel().getColumn(1).setCellEditor(editor);
    }
    
    
    private void initGpeSubjectButtons()
    {
        buttonGroup1.add(jRadioButton_Subject);
        buttonGroup1.add(jRadioButton_Group);       
    }
    
    DefaultTableModel jTableDM_Analysis;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Start;
    private javax.swing.JLabel jLabel_Analysis;
    private javax.swing.JLabel jLabel_AnalysisName;
    private javax.swing.JLabel jLabel_ConditionFolder;
    private javax.swing.JRadioButton jRadioButton_Group;
    private javax.swing.JRadioButton jRadioButton_Subject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Analysis;
    private javax.swing.JTextField jTextField_AnalysisName;
    private javax.swing.JTextField jTextField_ConditionFolder;
    // End of variables declaration//GEN-END:variables
}
