/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import structures.Project;
import structures.Preproc;
/**
 *
 * @author alba
 */
public class JPPreprocessing extends javax.swing.JPanel {

    /**
     * Creates new form JPreProcessing
     */
    public JPPreprocessing(JTPMain ctrl) {
        initComponents();
        controller = ctrl;
    }

    
    public void setGUI(Project proj)
    {
        project = proj;
        preproc = project.preproc;
        // fill GUI
    }
    
    public Project getGUI(Project proj)
    {
        proj.preproc.output_folder          = jTextField_OutputFolder.getText();
        proj.preproc.filter_algorithm       =  (String) JComboBox_FilterAlgo.getSelectedItem();
        
        boolean do_notch = jCheckBox_NotchFilter.isSelected();
        proj.preproc.do_notch[0]            = do_notch? 1 : 0;
        proj.preproc.notch_remove_armonics  = (String) jComboBox_RemoveArmonics.getSelectedItem();
        
        proj.preproc.notch_fcenter[0]       = Double.parseDouble(jTextField_NotchFilterCenter.getText());
        proj.preproc.notch_fspan[0]         = Double.parseDouble(jTextField__NotchFilterSpan.getText());
        
        proj.preproc.ff1_global[0]          = Double.parseDouble(jTextField_GlobalFilterLow.getText());
        proj.preproc.ff2_global[0]          = Double.parseDouble(jTextField_GlobalFilterHigh.getText());
        proj.preproc.ff1_eeg[0]             = Double.parseDouble(jTextField_EEGFilterLow.getText());
        proj.preproc.ff2_eeg[0]             = Double.parseDouble(jTextField_EEGFilterHigh.getText());
        proj.preproc.ff1_eog[0]             = Double.parseDouble(jTextField_EOGFilterLow.getText());
        proj.preproc.ff2_eog[0]             = Double.parseDouble(jTextField_EOGFilterHigh.getText());
        proj.preproc.ff1_emg[0]             = Double.parseDouble(jTextField_EMGFilterLow.getText());
        proj.preproc.ff2_emg[0]             = Double.parseDouble(jTextField_EMGFilterHigh.getText());
        
        proj.preproc.rt.eve1_type               = jTextField_Evt1Type.getText();
        proj.preproc.rt.eve2_type               = jTextField_Evt2Type.getText();
        proj.preproc.rt.allowed_tw_ms.min[0]    = Double.parseDouble(jTextField_AllowTwMin.getText());
        proj.preproc.rt.allowed_tw_ms.max[0]    = Double.parseDouble(jTextField_AllowTwMax.getText());
        proj.preproc.rt.output_folder           = jTextField_ReacTimesOutputFolder.getText();
        
        proj.preproc.marker_type.begin_trial    = jTextField_TrialMarkersBeginType.getText(); 
        proj.preproc.marker_type.end_trial      = jTextField_TrialMarkersEndType.getText(); 
        proj.preproc.marker_type.begin_baseline = jTextField_BaselineBeginType.getText(); 
        proj.preproc.marker_type.end_baseline   = jTextField_BaselineEndType.getText(); 

        proj.preproc.insert_begin_trial.target_event_types[0]       = jTextField_TrialMarkersBeginEvtTypes.getText(); 
        proj.preproc.insert_begin_trial.delay.s[0]                  = Double.parseDouble(jTextField_TrialMarkersBeginDelay.getText()); 
        proj.preproc.insert_end_trial.target_event_types[0]         = jTextField_TrialMarkersEndEvtTypes.getText(); 
        proj.preproc.insert_end_trial.delay.s[0]                    = Double.parseDouble(jTextField_TrialMarkersEndDelay.getText()); 
        proj.preproc.insert_begin_baseline.target_event_types[0]    = jTextField_BaselineBeginEvtTypes.getText(); 
        proj.preproc.insert_begin_baseline.delay.s[0]               = Double.parseDouble(jTextField_BaselineBeginDelay.getText()); 
        proj.preproc.insert_end_baseline.target_event_types[0]      = jTextField_BaselineEndEvtTypes.getText(); 
        proj.preproc.insert_end_baseline.delay.s[0]                 = Double.parseDouble(jTextField_BaselineEndDelay.getText()); 
        
        proj.preproc.insert_block.trials_per_block[0]               = Double.parseDouble(jTextField_BlockMarkers.getText()); 
        
        // montage_list ??

        return proj;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPpreproc = new javax.swing.JPanel();
        jLabel_GlobalFilter = new javax.swing.JLabel();
        jLabel_FilterAlgo = new javax.swing.JLabel();
        JComboBox_FilterAlgo = new javax.swing.JComboBox();
        jLabel_GlobalFilterLow = new javax.swing.JLabel();
        jTextField_GlobalFilterLow = new javax.swing.JTextField();
        jLabel_GlobalFilterHigh = new javax.swing.JLabel();
        jTextField_GlobalFilterHigh = new javax.swing.JTextField();
        jLabel_OutputFolder = new javax.swing.JLabel();
        jTextField_OutputFolder = new javax.swing.JTextField();
        jLabel_NotchFilterCenter = new javax.swing.JLabel();
        jTextField_NotchFilterCenter = new javax.swing.JTextField();
        jLabel_NotchFilter = new javax.swing.JLabel();
        jCheckBox_NotchFilter = new javax.swing.JCheckBox();
        jLabel_NotchFilterSpan = new javax.swing.JLabel();
        jTextField__NotchFilterSpan = new javax.swing.JTextField();
        jLabel_RemoveArmonics = new javax.swing.JLabel();
        jComboBox_RemoveArmonics = new javax.swing.JComboBox();
        jLabel_EEGFilter = new javax.swing.JLabel();
        jLabel_EEGFilterLow = new javax.swing.JLabel();
        jTextField_EEGFilterLow = new javax.swing.JTextField();
        jLabel_EEGFilterHigh = new javax.swing.JLabel();
        jTextField_EEGFilterHigh = new javax.swing.JTextField();
        jLabel_EOGFilter = new javax.swing.JLabel();
        jLabel_EOGFilterLow = new javax.swing.JLabel();
        jTextField_EOGFilterLow = new javax.swing.JTextField();
        jLabel_EOGFilterHigh = new javax.swing.JLabel();
        jTextField_EOGFilterHigh = new javax.swing.JTextField();
        jLabel_EMGFilter = new javax.swing.JLabel();
        jLabel_EMGFilterLow = new javax.swing.JLabel();
        jTextField_EMGFilterLow = new javax.swing.JTextField();
        jLabel_EMGFilterHigh = new javax.swing.JLabel();
        jTextField_EMGFilterHigh = new javax.swing.JTextField();
        jLabel_ReactionTimes = new javax.swing.JLabel();
        jLabel_Evt1Type = new javax.swing.JLabel();
        jTextField_Evt1Type = new javax.swing.JTextField();
        jLabel_Evt2Type = new javax.swing.JLabel();
        jTextField_Evt2Type = new javax.swing.JTextField();
        jLabel_AllowTwMin = new javax.swing.JLabel();
        jTextField_AllowTwMin = new javax.swing.JTextField();
        jLabel_AllowTwMax = new javax.swing.JLabel();
        jTextField_AllowTwMax = new javax.swing.JTextField();
        jLabel_ReacTimesOutputFolder = new javax.swing.JLabel();
        jTextField_ReacTimesOutputFolder = new javax.swing.JTextField();
        jLabel_BaselineTrialsMarkers = new javax.swing.JLabel();
        jLabel_TrialMarkersBegin = new javax.swing.JLabel();
        jTextField_TrialMarkersBegin = new javax.swing.JTextField();
        jLabel_BaselineBeginType = new javax.swing.JLabel();
        jTextField_BaselineBeginType = new javax.swing.JTextField();
        jTextField_TrialMarkersBeginEvtTypes = new javax.swing.JTextField();
        jLabel_Trial = new javax.swing.JLabel();
        jLabel_Baseline = new javax.swing.JLabel();
        jLabel_TrialMarkersBeginDelay = new javax.swing.JLabel();
        jTextField_TrialMarkersBeginDelay = new javax.swing.JTextField();
        jLabel_TrialMarkersBeginEvtTypes = new javax.swing.JLabel();
        jLabel_BlockMarkers = new javax.swing.JLabel();
        jTextField_BlockMarkers = new javax.swing.JTextField();
        jLabel_Montage = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_Montage2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea_Montage1 = new javax.swing.JTextArea();
        jLabel_TrialMarkersEnd = new javax.swing.JLabel();
        jTextField_TrialMarkersEnd = new javax.swing.JTextField();
        jLabel_BaselineEndType = new javax.swing.JLabel();
        jTextField_BaselineEndType = new javax.swing.JTextField();
        jTextField_TrialMarkersEndEvtTypes = new javax.swing.JTextField();
        jLabel_TrialMarkersEndDelay = new javax.swing.JLabel();
        jTextField_TrialMarkersEndDelay = new javax.swing.JTextField();
        jLabel_TrialMarkersEndEvtTypes = new javax.swing.JLabel();
        jLabel_BaselineBegin = new javax.swing.JLabel();
        jTextField_BaselineBegin = new javax.swing.JTextField();
        jLabel_BaselineEnd = new javax.swing.JLabel();
        jTextField_BaselineEnd = new javax.swing.JTextField();
        jTextField_BaselineEndEvtTypes = new javax.swing.JTextField();
        jTextField_BaselineBeginEvtTypes = new javax.swing.JTextField();
        jLabel_BaselineEndDelay = new javax.swing.JLabel();
        jTextField_BaselineEndDelay = new javax.swing.JTextField();
        jLabel_BaselineEndEvtTypes = new javax.swing.JLabel();
        jLabel_BaselineBeginDelay = new javax.swing.JLabel();
        jTextField_BaselineBeginDelay = new javax.swing.JTextField();
        jLabel_BaselineBeginEvtTypes = new javax.swing.JLabel();
        jTextField_TrialMarkersBeginType = new javax.swing.JTextField();
        jLabel_TrialMarkersBeginType = new javax.swing.JLabel();
        jLabel_TrialMarkersEndType = new javax.swing.JLabel();
        jTextField_TrialMarkersEndType = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1143, 779));

        jPpreproc.setName("preproc"); // NOI18N
        jPpreproc.setPreferredSize(new java.awt.Dimension(1150, 750));

        jLabel_GlobalFilter.setText("GLOBAL FILTER");

        jLabel_FilterAlgo.setText("filter algorythm");

        JComboBox_FilterAlgo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JComboBox_FilterAlgo.setName("filter_algorithm"); // NOI18N
        JComboBox_FilterAlgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBox_FilterAlgoActionPerformed(evt);
            }
        });

        jLabel_GlobalFilterLow.setText("low");

        jTextField_GlobalFilterLow.setText("jTextField1");
        jTextField_GlobalFilterLow.setName("ff1_global"); // NOI18N

        jLabel_GlobalFilterHigh.setText("high");

        jTextField_GlobalFilterHigh.setText("jTextField1");
        jTextField_GlobalFilterHigh.setName("ff2_global"); // NOI18N

        jLabel_OutputFolder.setText("output folder");

        jTextField_OutputFolder.setText("jTextField1");
        jTextField_OutputFolder.setName("jTextField_OutputFolder"); // NOI18N

        jLabel_NotchFilterCenter.setText("center");

        jTextField_NotchFilterCenter.setText("jTextField1");
        jTextField_NotchFilterCenter.setName("notch_fcenter"); // NOI18N

        jLabel_NotchFilter.setText("NOTCH FILTER");

        jCheckBox_NotchFilter.setName("do_notch"); // NOI18N

        jLabel_NotchFilterSpan.setText("span");

        jTextField__NotchFilterSpan.setText("jTextField1");
        jTextField__NotchFilterSpan.setName("notch_fspan"); // NOI18N
        jTextField__NotchFilterSpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField__NotchFilterSpanActionPerformed(evt);
            }
        });

        jLabel_RemoveArmonics.setText("remove armonics");

        jComboBox_RemoveArmonics.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_RemoveArmonics.setName("notch_remove_armonics"); // NOI18N
        jComboBox_RemoveArmonics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_RemoveArmonicsActionPerformed(evt);
            }
        });

        jLabel_EEGFilter.setText("EEG FILTER");

        jLabel_EEGFilterLow.setText("low");

        jTextField_EEGFilterLow.setText("jTextField1");
        jTextField_EEGFilterLow.setName("ff1_eeg"); // NOI18N

        jLabel_EEGFilterHigh.setText("high");

        jTextField_EEGFilterHigh.setText("jTextField1");
        jTextField_EEGFilterHigh.setName("ff2_eeg"); // NOI18N

        jLabel_EOGFilter.setText("EOG FILTER");

        jLabel_EOGFilterLow.setText("low");

        jTextField_EOGFilterLow.setText("jTextField1");
        jTextField_EOGFilterLow.setName("ff1_eog"); // NOI18N

        jLabel_EOGFilterHigh.setText("high");

        jTextField_EOGFilterHigh.setText("jTextField1");
        jTextField_EOGFilterHigh.setName("ff2_eog"); // NOI18N
        jTextField_EOGFilterHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EOGFilterHighActionPerformed(evt);
            }
        });

        jLabel_EMGFilter.setText("EMG FILTER");

        jLabel_EMGFilterLow.setText("low");

        jTextField_EMGFilterLow.setText("jTextField1");
        jTextField_EMGFilterLow.setName("ff1_emg"); // NOI18N

        jLabel_EMGFilterHigh.setText("high");

        jTextField_EMGFilterHigh.setText("jTextField1");
        jTextField_EMGFilterHigh.setName("ff2_emg"); // NOI18N

        jLabel_ReactionTimes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_ReactionTimes.setText("Reaction Times");

        jLabel_Evt1Type.setText("eve1 type");

        jTextField_Evt1Type.setText("jTextField1");
        jTextField_Evt1Type.setName("eve1_type"); // NOI18N

        jLabel_Evt2Type.setText("eve 2 type");

        jTextField_Evt2Type.setText("jTextField1");
        jTextField_Evt2Type.setName("eve2_type"); // NOI18N

        jLabel_AllowTwMin.setText("allowed tw MIN [ms]");

        jTextField_AllowTwMin.setText("jTextField1");
        jTextField_AllowTwMin.setName("allowed_tw_ms_min"); // NOI18N

        jLabel_AllowTwMax.setText("allowed tw MAX [ms]");

        jTextField_AllowTwMax.setText("jTextField1");
        jTextField_AllowTwMax.setName("allowed_tw_ms_max"); // NOI18N

        jLabel_ReacTimesOutputFolder.setText("output folder");

        jTextField_ReacTimesOutputFolder.setText("jTextField1");
        jTextField_ReacTimesOutputFolder.setName("output_folder"); // NOI18N

        jLabel_BaselineTrialsMarkers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_BaselineTrialsMarkers.setText("Baseline and Trials Markers");

        jLabel_TrialMarkersBegin.setText("begin");

        jTextField_TrialMarkersBegin.setText("jTextField1");
        jTextField_TrialMarkersBegin.setName("begin_trial"); // NOI18N

        jLabel_BaselineBeginType.setText("type");

        jTextField_BaselineBeginType.setText("jTextField1");

        jTextField_TrialMarkersBeginEvtTypes.setText("jTextField1");

        jLabel_Trial.setText("Trial");

        jLabel_Baseline.setText("Baseline");

        jLabel_TrialMarkersBeginDelay.setText("delay");

        jTextField_TrialMarkersBeginDelay.setText("jTextField1");

        jLabel_TrialMarkersBeginEvtTypes.setText("event types");

        jLabel_BlockMarkers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_BlockMarkers.setText("Block markers");

        jTextField_BlockMarkers.setText("jTextField1");

        jLabel_Montage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Montage.setText("Montages");

        jTextArea_Montage2.setColumns(20);
        jTextArea_Montage2.setRows(5);
        jScrollPane4.setViewportView(jTextArea_Montage2);

        jTextArea_Montage1.setColumns(20);
        jTextArea_Montage1.setRows(5);
        jScrollPane5.setViewportView(jTextArea_Montage1);

        jLabel_TrialMarkersEnd.setText("end");

        jTextField_TrialMarkersEnd.setText("jTextField1");
        jTextField_TrialMarkersEnd.setName("begin_trial"); // NOI18N

        jLabel_BaselineEndType.setText("type");

        jTextField_BaselineEndType.setText("jTextField1");

        jTextField_TrialMarkersEndEvtTypes.setText("jTextField1");

        jLabel_TrialMarkersEndDelay.setText("delay");

        jTextField_TrialMarkersEndDelay.setText("jTextField1");

        jLabel_TrialMarkersEndEvtTypes.setText("event types");

        jLabel_BaselineBegin.setText("begin");

        jTextField_BaselineBegin.setText("jTextField1");
        jTextField_BaselineBegin.setName("begin_trial"); // NOI18N

        jLabel_BaselineEnd.setText("end");

        jTextField_BaselineEnd.setText("jTextField1");
        jTextField_BaselineEnd.setName("begin_trial"); // NOI18N

        jTextField_BaselineEndEvtTypes.setText("jTextField1");

        jTextField_BaselineBeginEvtTypes.setText("jTextField1");

        jLabel_BaselineEndDelay.setText("delay");

        jTextField_BaselineEndDelay.setText("jTextField1");

        jLabel_BaselineEndEvtTypes.setText("event types");

        jLabel_BaselineBeginDelay.setText("delay");

        jTextField_BaselineBeginDelay.setText("jTextField1");

        jLabel_BaselineBeginEvtTypes.setText("event types");

        jTextField_TrialMarkersBeginType.setText("jTextField1");

        jLabel_TrialMarkersBeginType.setText("type");

        jLabel_TrialMarkersEndType.setText("type");

        jTextField_TrialMarkersEndType.setText("jTextField1");

        javax.swing.GroupLayout jPpreprocLayout = new javax.swing.GroupLayout(jPpreproc);
        jPpreproc.setLayout(jPpreprocLayout);
        jPpreprocLayout.setHorizontalGroup(
            jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpreprocLayout.createSequentialGroup()
                .addComponent(jLabel_Montage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPpreprocLayout.createSequentialGroup()
                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPpreprocLayout.createSequentialGroup()
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Trial, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Baseline, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPpreprocLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPpreprocLayout.createSequentialGroup()
                                        .addComponent(jLabel_TrialMarkersBegin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_TrialMarkersBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField_BlockMarkers, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(262, 262, 262))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPpreprocLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPpreprocLayout.createSequentialGroup()
                                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPpreprocLayout.createSequentialGroup()
                                                .addComponent(jLabel_BaselineBegin)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField_BaselineBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPpreprocLayout.createSequentialGroup()
                                                .addComponent(jLabel_BaselineEnd)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField_BaselineEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(25, 25, 25)
                                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPpreprocLayout.createSequentialGroup()
                                                .addComponent(jLabel_TrialMarkersBeginType, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_TrialMarkersBeginType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPpreprocLayout.createSequentialGroup()
                                                .addComponent(jLabel_TrialMarkersEndType, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_TrialMarkersEndType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPpreprocLayout.createSequentialGroup()
                                                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel_BaselineBeginType, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel_BaselineEndType, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_BaselineEndType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_BaselineBeginType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel_BaselineEndDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_BaselineBeginDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPpreprocLayout.createSequentialGroup()
                                                .addComponent(jTextField_BaselineEndDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(52, 52, 52)
                                                .addComponent(jLabel_BaselineEndEvtTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_BaselineEndEvtTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPpreprocLayout.createSequentialGroup()
                                                .addComponent(jTextField_BaselineBeginDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(52, 52, 52)
                                                .addComponent(jLabel_BaselineBeginEvtTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_BaselineBeginEvtTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPpreprocLayout.createSequentialGroup()
                                        .addComponent(jLabel_TrialMarkersEnd)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_TrialMarkersEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(153, 153, 153)
                                        .addComponent(jLabel_TrialMarkersEndDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_TrialMarkersEndDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel_TrialMarkersEndEvtTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_TrialMarkersEndEvtTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel_ReactionTimes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_BaselineTrialsMarkers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_BlockMarkers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPpreprocLayout.createSequentialGroup()
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_GlobalFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPpreprocLayout.createSequentialGroup()
                                .addComponent(jLabel_NotchFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox_NotchFilter)))
                        .addGap(21, 21, 21)
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPpreprocLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel_OutputFolder)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_OutputFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel_FilterAlgo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JComboBox_FilterAlgo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPpreprocLayout.createSequentialGroup()
                                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPpreprocLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel_GlobalFilterLow, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_GlobalFilterLow, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_GlobalFilterHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel_NotchFilterCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(145, 145, 145)
                                .addComponent(jLabel_RemoveArmonics, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_RemoveArmonics, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPpreprocLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel_Evt1Type)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPpreprocLayout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(jLabel_TrialMarkersBeginDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_TrialMarkersBeginDelay, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel_TrialMarkersBeginEvtTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_TrialMarkersBeginEvtTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPpreprocLayout.createSequentialGroup()
                                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPpreprocLayout.createSequentialGroup()
                                        .addComponent(jTextField_Evt1Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_Evt2Type, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Evt2Type, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_AllowTwMin, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_AllowTwMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel_AllowTwMax, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPpreprocLayout.createSequentialGroup()
                                        .addComponent(jTextField_NotchFilterCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_NotchFilterSpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_GlobalFilterHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField__NotchFilterSpan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPpreprocLayout.createSequentialGroup()
                                        .addComponent(jLabel_EEGFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_EEGFilterLow, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jTextField_EEGFilterLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_EEGFilterHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_EEGFilterHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPpreprocLayout.createSequentialGroup()
                                        .addComponent(jLabel_EOGFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_EOGFilterLow, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jTextField_EOGFilterLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_EOGFilterHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_EOGFilterHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPpreprocLayout.createSequentialGroup()
                                        .addComponent(jLabel_EMGFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_EMGFilterLow, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jTextField_EMGFilterLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_EMGFilterHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_EMGFilterHigh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPpreprocLayout.createSequentialGroup()
                                        .addComponent(jTextField_AllowTwMax, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_ReacTimesOutputFolder)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_ReacTimesOutputFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(322, 322, 322))
        );
        jPpreprocLayout.setVerticalGroup(
            jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpreprocLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPpreprocLayout.createSequentialGroup()
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPpreprocLayout.createSequentialGroup()
                                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_FilterAlgo)
                                    .addComponent(JComboBox_FilterAlgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_OutputFolder)
                                    .addComponent(jTextField_OutputFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_GlobalFilterLow)
                                    .addComponent(jTextField_GlobalFilterLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_GlobalFilterHigh)
                                    .addComponent(jTextField_GlobalFilterHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_GlobalFilter))
                                .addGap(18, 18, 18)
                                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_NotchFilterCenter)
                                    .addComponent(jTextField_NotchFilterCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_NotchFilter)
                                    .addComponent(jLabel_NotchFilterSpan)
                                    .addComponent(jTextField__NotchFilterSpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_RemoveArmonics)
                                    .addComponent(jComboBox_RemoveArmonics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jCheckBox_NotchFilter, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(49, 49, 49)
                        .addComponent(jLabel_ReactionTimes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Evt1Type)
                            .addComponent(jTextField_Evt1Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Evt2Type)
                            .addComponent(jTextField_Evt2Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_AllowTwMin)
                            .addComponent(jTextField_AllowTwMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_AllowTwMax)))
                    .addGroup(jPpreprocLayout.createSequentialGroup()
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_EEGFilterLow)
                            .addComponent(jTextField_EEGFilterLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_EEGFilterHigh)
                            .addComponent(jTextField_EEGFilterHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_EEGFilter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_EOGFilterLow)
                            .addComponent(jTextField_EOGFilterLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_EOGFilterHigh)
                            .addComponent(jTextField_EOGFilterHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_EOGFilter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_EMGFilterLow)
                            .addComponent(jTextField_EMGFilterLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_EMGFilterHigh)
                            .addComponent(jTextField_EMGFilterHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_EMGFilter))
                        .addGap(77, 77, 77)
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_AllowTwMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ReacTimesOutputFolder)
                            .addComponent(jTextField_ReacTimesOutputFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55)
                .addComponent(jLabel_BaselineTrialsMarkers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPpreprocLayout.createSequentialGroup()
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_TrialMarkersBegin)
                                .addComponent(jTextField_TrialMarkersBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_Trial)
                                .addComponent(jLabel_TrialMarkersBeginDelay)
                                .addComponent(jTextField_TrialMarkersBeginDelay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_TrialMarkersBeginEvtTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_TrialMarkersBeginEvtTypes)))
                        .addGap(5, 5, 5)
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_TrialMarkersEnd)
                                .addComponent(jTextField_TrialMarkersEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_TrialMarkersEndDelay)
                                .addComponent(jTextField_TrialMarkersEndDelay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_TrialMarkersEndEvtTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_TrialMarkersEndEvtTypes)))
                        .addGap(21, 21, 21)
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Baseline)
                            .addGroup(jPpreprocLayout.createSequentialGroup()
                                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_BaselineBegin)
                                        .addComponent(jTextField_BaselineBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_BaselineBeginDelay)
                                        .addComponent(jTextField_BaselineBeginDelay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_BaselineBeginType)
                                        .addComponent(jTextField_BaselineBeginType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField_BaselineBeginEvtTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_BaselineBeginEvtTypes)))
                                .addGap(5, 5, 5)
                                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_BaselineEnd)
                                        .addComponent(jTextField_BaselineEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_BaselineEndDelay)
                                        .addComponent(jTextField_BaselineEndDelay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_BaselineEndType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_BaselineEndType))
                                    .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField_BaselineEndEvtTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_BaselineEndEvtTypes))))))
                    .addGroup(jPpreprocLayout.createSequentialGroup()
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_TrialMarkersBeginType)
                            .addComponent(jTextField_TrialMarkersBeginType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_TrialMarkersEndType)
                            .addComponent(jTextField_TrialMarkersEndType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_BlockMarkers)
                    .addComponent(jTextField_BlockMarkers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPpreprocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Montage)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPpreproc, javax.swing.GroupLayout.PREFERRED_SIZE, 1151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPpreproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_EOGFilterHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EOGFilterHighActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EOGFilterHighActionPerformed

    private void jComboBox_RemoveArmonicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_RemoveArmonicsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_RemoveArmonicsActionPerformed

    private void jTextField__NotchFilterSpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField__NotchFilterSpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField__NotchFilterSpanActionPerformed

    private void JComboBox_FilterAlgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBox_FilterAlgoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBox_FilterAlgoActionPerformed
    
    private JTPMain controller;
    private Project project;
    private Preproc preproc;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JComboBox_FilterAlgo;
    private javax.swing.JCheckBox jCheckBox_NotchFilter;
    private javax.swing.JComboBox jComboBox_RemoveArmonics;
    private javax.swing.JLabel jLabel_AllowTwMax;
    private javax.swing.JLabel jLabel_AllowTwMin;
    private javax.swing.JLabel jLabel_Baseline;
    private javax.swing.JLabel jLabel_BaselineBegin;
    private javax.swing.JLabel jLabel_BaselineBeginDelay;
    private javax.swing.JLabel jLabel_BaselineBeginEvtTypes;
    private javax.swing.JLabel jLabel_BaselineBeginType;
    private javax.swing.JLabel jLabel_BaselineEnd;
    private javax.swing.JLabel jLabel_BaselineEndDelay;
    private javax.swing.JLabel jLabel_BaselineEndEvtTypes;
    private javax.swing.JLabel jLabel_BaselineEndType;
    private javax.swing.JLabel jLabel_BaselineTrialsMarkers;
    private javax.swing.JLabel jLabel_BlockMarkers;
    private javax.swing.JLabel jLabel_EEGFilter;
    private javax.swing.JLabel jLabel_EEGFilterHigh;
    private javax.swing.JLabel jLabel_EEGFilterLow;
    private javax.swing.JLabel jLabel_EMGFilter;
    private javax.swing.JLabel jLabel_EMGFilterHigh;
    private javax.swing.JLabel jLabel_EMGFilterLow;
    private javax.swing.JLabel jLabel_EOGFilter;
    private javax.swing.JLabel jLabel_EOGFilterHigh;
    private javax.swing.JLabel jLabel_EOGFilterLow;
    private javax.swing.JLabel jLabel_Evt1Type;
    private javax.swing.JLabel jLabel_Evt2Type;
    private javax.swing.JLabel jLabel_FilterAlgo;
    private javax.swing.JLabel jLabel_GlobalFilter;
    private javax.swing.JLabel jLabel_GlobalFilterHigh;
    private javax.swing.JLabel jLabel_GlobalFilterLow;
    private javax.swing.JLabel jLabel_Montage;
    private javax.swing.JLabel jLabel_NotchFilter;
    private javax.swing.JLabel jLabel_NotchFilterCenter;
    private javax.swing.JLabel jLabel_NotchFilterSpan;
    private javax.swing.JLabel jLabel_OutputFolder;
    private javax.swing.JLabel jLabel_ReacTimesOutputFolder;
    private javax.swing.JLabel jLabel_ReactionTimes;
    private javax.swing.JLabel jLabel_RemoveArmonics;
    private javax.swing.JLabel jLabel_Trial;
    private javax.swing.JLabel jLabel_TrialMarkersBegin;
    private javax.swing.JLabel jLabel_TrialMarkersBeginDelay;
    private javax.swing.JLabel jLabel_TrialMarkersBeginEvtTypes;
    private javax.swing.JLabel jLabel_TrialMarkersBeginType;
    private javax.swing.JLabel jLabel_TrialMarkersEnd;
    private javax.swing.JLabel jLabel_TrialMarkersEndDelay;
    private javax.swing.JLabel jLabel_TrialMarkersEndEvtTypes;
    private javax.swing.JLabel jLabel_TrialMarkersEndType;
    private javax.swing.JPanel jPpreproc;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea_Montage1;
    private javax.swing.JTextArea jTextArea_Montage2;
    private javax.swing.JTextField jTextField_AllowTwMax;
    private javax.swing.JTextField jTextField_AllowTwMin;
    private javax.swing.JTextField jTextField_BaselineBegin;
    private javax.swing.JTextField jTextField_BaselineBeginDelay;
    private javax.swing.JTextField jTextField_BaselineBeginEvtTypes;
    private javax.swing.JTextField jTextField_BaselineBeginType;
    private javax.swing.JTextField jTextField_BaselineEnd;
    private javax.swing.JTextField jTextField_BaselineEndDelay;
    private javax.swing.JTextField jTextField_BaselineEndEvtTypes;
    private javax.swing.JTextField jTextField_BaselineEndType;
    private javax.swing.JTextField jTextField_BlockMarkers;
    private javax.swing.JTextField jTextField_EEGFilterHigh;
    private javax.swing.JTextField jTextField_EEGFilterLow;
    private javax.swing.JTextField jTextField_EMGFilterHigh;
    private javax.swing.JTextField jTextField_EMGFilterLow;
    private javax.swing.JTextField jTextField_EOGFilterHigh;
    private javax.swing.JTextField jTextField_EOGFilterLow;
    private javax.swing.JTextField jTextField_Evt1Type;
    private javax.swing.JTextField jTextField_Evt2Type;
    private javax.swing.JTextField jTextField_GlobalFilterHigh;
    private javax.swing.JTextField jTextField_GlobalFilterLow;
    private javax.swing.JTextField jTextField_NotchFilterCenter;
    private javax.swing.JTextField jTextField_OutputFolder;
    private javax.swing.JTextField jTextField_ReacTimesOutputFolder;
    private javax.swing.JTextField jTextField_TrialMarkersBegin;
    private javax.swing.JTextField jTextField_TrialMarkersBeginDelay;
    private javax.swing.JTextField jTextField_TrialMarkersBeginEvtTypes;
    private javax.swing.JTextField jTextField_TrialMarkersBeginType;
    private javax.swing.JTextField jTextField_TrialMarkersEnd;
    private javax.swing.JTextField jTextField_TrialMarkersEndDelay;
    private javax.swing.JTextField jTextField_TrialMarkersEndEvtTypes;
    private javax.swing.JTextField jTextField_TrialMarkersEndType;
    private javax.swing.JTextField jTextField__NotchFilterSpan;
    // End of variables declaration//GEN-END:variables
}
