/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.DefaultCellEditor;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import structures.Project;
import structures.Study;
import structures.Subjects;

/**
 *
 * @author PHilt
 */
public class JPStudyDesign extends javax.swing.JPanel {

    private JTPMain controller;
    public Study study;
    public Project project;
    
    
    public JPStudyDesign(JTPMain ctrl) 
    {
        controller = ctrl;
        initComponents();
        initExpFactorsTable();
        initListFileMatch();
        initDesignErpTable();
    }
    

    public void setGUI(Project proj)
    {
        project = proj;
        study = project.study;
    }
    
    public Project getGUI(Project proj)
    {
        proj.study.filename = jTextField_StudyFilename.getText();
        
        boolean do_recompute    = jCheckBox_DoRecompute.isSelected();
        boolean do_erp          = jCheckBox_DoErp.isSelected();
        boolean do_ersp         = jCheckBox_DoErsp.isSelected();
        boolean do_erpim        = jCheckBox_DoErpim.isSelected();
        boolean do_spec         = jCheckBox_DoSpec.isSelected();
        proj.study.precompute.recompute = do_recompute? "on" : "off"; 
        proj.study.precompute.do_erp    = do_erp? "on" : "off"; 
        proj.study.precompute.do_ersp   = do_ersp? "on" : "off"; 
        proj.study.precompute.do_erpim  = do_erpim? "on" : "off"; 
        proj.study.precompute.do_spec   = do_spec? "on" : "off"; 
        
        // erpim and spec params ?
        
        for (int i = 0; i < jTableDM_ExpFactors.getColumnCount(); i++) 
        {
            proj.study.factors[i].factor        = (String) jTable_ExpFactors.getModel().getValueAt(i,0);
            proj.study.factors[i].level         = (String) jTable_ExpFactors.getModel().getValueAt(i,1);
            //proj.study.factors[i].file_match    = (String) jTable_ExpFactors.getModel().getValueAt(i,2);
        }
        
        for (int i = 0; i < jTableDM_Design.getColumnCount(); i++) 
        {
            proj.study.design[i].name               = (String) jTable_Design.getModel().getValueAt(i,0);
            proj.study.design[i].factor1_name       = (String) jTable_Design.getModel().getValueAt(i,1);
            proj.study.design[i].factor1_pairing    = (String) jTable_Design.getModel().getValueAt(i,2);
            //proj.study.design[i].factor1_levels     = (String) jTable_Design.getModel().getValueAt(i,3);  
            proj.study.design[i].factor2_name       = (String) jTable_Design.getModel().getValueAt(i,4);
            proj.study.design[i].factor2_pairing    = (String) jTable_Design.getModel().getValueAt(i,5);
            //proj.study.design[i].factor2_levels     = (String) jTable_Design.getModel().getValueAt(i,5); 
        }
        
        return proj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPstudy_design = new javax.swing.JPanel();
        jLabel_ExpFactors = new javax.swing.JLabel();
        jButton_ExpFactorsRemove = new javax.swing.JButton();
        jButton_ExpFactorsNew = new javax.swing.JButton();
        jButton_FileMatchApply = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable_ExpFactors = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList_FileMatch = new javax.swing.JList();
        jLabel_Design = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable_Design = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        jList_DesignLevels2 = new javax.swing.JList();
        jScrollPane13 = new javax.swing.JScrollPane();
        jList_DesignLevels1 = new javax.swing.JList();
        jLabel_DesignLevels1 = new javax.swing.JLabel();
        jLabel_DesignLevels2 = new javax.swing.JLabel();
        jButton_DesignNew = new javax.swing.JButton();
        jButton_DesignRemove = new javax.swing.JButton();
        jButton_DesignApply1 = new javax.swing.JButton();
        jButton_DesignApply2 = new javax.swing.JButton();
        jLabel_FileMatch = new javax.swing.JLabel();
        jCheckBox_DoRecompute = new javax.swing.JCheckBox();
        jCheckBox_DoErsp = new javax.swing.JCheckBox();
        jCheckBox_DoErp = new javax.swing.JCheckBox();
        jCheckBox_DoSpec = new javax.swing.JCheckBox();
        jCheckBox_DoErpim = new javax.swing.JCheckBox();
        jLabel_StudyFilename = new javax.swing.JLabel();
        jTextField_StudyFilename = new javax.swing.JTextField();
        jButton_ExpFactorsApply = new javax.swing.JButton();

        jPstudy_design.setName("study_design"); // NOI18N

        jLabel_ExpFactors.setText("EXP. FACTORS");

        jButton_ExpFactorsRemove.setText("R");
        jButton_ExpFactorsRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExpFactorsRemoveActionPerformed(evt);
            }
        });

        jButton_ExpFactorsNew.setText("N");
        jButton_ExpFactorsNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExpFactorsNewActionPerformed(evt);
            }
        });

        jButton_FileMatchApply.setText("Apply");
        jButton_FileMatchApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FileMatchApplyActionPerformed(evt);
            }
        });

        jTable_ExpFactors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "factor", "level", "file match"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_ExpFactors.getTableHeader().setReorderingAllowed(false);
        jScrollPane12.setViewportView(jTable_ExpFactors);

        jList_FileMatch.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jList_FileMatch);

        jLabel_Design.setText("DESIGN");

        jTable_Design.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "factor 1", "pair1", "level 1", "factor 2", "pair 2", "level 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_Design.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(jTable_Design);

        jList_DesignLevels2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(jList_DesignLevels2);

        jList_DesignLevels1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane13.setViewportView(jList_DesignLevels1);

        jLabel_DesignLevels1.setText(" 1");

        jLabel_DesignLevels2.setText("Levels 2");

        jButton_DesignNew.setText("N");
        jButton_DesignNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DesignNewActionPerformed(evt);
            }
        });

        jButton_DesignRemove.setText("R");
        jButton_DesignRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DesignRemoveActionPerformed(evt);
            }
        });

        jButton_DesignApply1.setText("Apply");
        jButton_DesignApply1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DesignApply1ActionPerformed(evt);
            }
        });

        jButton_DesignApply2.setText("Apply");
        jButton_DesignApply2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DesignApply2ActionPerformed(evt);
            }
        });

        jLabel_FileMatch.setText("File match");

        jCheckBox_DoRecompute.setText("recompute");

        jCheckBox_DoErsp.setText("do ersp");

        jCheckBox_DoErp.setText("do erp");

        jCheckBox_DoSpec.setText("do spec");

        jCheckBox_DoErpim.setText("do erpim");

        jLabel_StudyFilename.setText("Study filename");

        jTextField_StudyFilename.setText("jTextField1");

        jButton_ExpFactorsApply.setText("A");
        jButton_ExpFactorsApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExpFactorsApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPstudy_designLayout = new javax.swing.GroupLayout(jPstudy_design);
        jPstudy_design.setLayout(jPstudy_designLayout);
        jPstudy_designLayout.setHorizontalGroup(
            jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPstudy_designLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPstudy_designLayout.createSequentialGroup()
                        .addComponent(jLabel_Design, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                            .addGroup(jPstudy_designLayout.createSequentialGroup()
                                .addComponent(jButton_DesignNew)
                                .addGap(3, 3, 3)
                                .addComponent(jButton_DesignRemove)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane9))
                        .addGap(18, 18, 18)
                        .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPstudy_designLayout.createSequentialGroup()
                                .addComponent(jLabel_DesignLevels1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_DesignApply1))
                            .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPstudy_designLayout.createSequentialGroup()
                                    .addComponent(jLabel_FileMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton_FileMatchApply))))
                        .addGap(45, 45, 45)
                        .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPstudy_designLayout.createSequentialGroup()
                                .addComponent(jLabel_DesignLevels2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jButton_DesignApply2))
                            .addComponent(jScrollPane11))
                        .addGap(109, 109, 109))
                    .addGroup(jPstudy_designLayout.createSequentialGroup()
                        .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_ExpFactors, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_StudyFilename))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPstudy_designLayout.createSequentialGroup()
                                .addComponent(jCheckBox_DoRecompute)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox_DoErp)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox_DoErsp)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox_DoErpim)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox_DoSpec))
                            .addGroup(jPstudy_designLayout.createSequentialGroup()
                                .addComponent(jButton_ExpFactorsNew)
                                .addGap(3, 3, 3)
                                .addComponent(jButton_ExpFactorsRemove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_ExpFactorsApply))
                            .addComponent(jTextField_StudyFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))))
        );
        jPstudy_designLayout.setVerticalGroup(
            jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPstudy_designLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_StudyFilename)
                    .addComponent(jTextField_StudyFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_DoRecompute)
                    .addComponent(jCheckBox_DoErsp)
                    .addComponent(jCheckBox_DoErp)
                    .addComponent(jCheckBox_DoSpec)
                    .addComponent(jCheckBox_DoErpim))
                .addGap(73, 73, 73)
                .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPstudy_designLayout.createSequentialGroup()
                        .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_ExpFactorsRemove)
                            .addComponent(jButton_ExpFactorsNew)
                            .addComponent(jLabel_ExpFactors)
                            .addComponent(jButton_ExpFactorsApply))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_DesignRemove)
                            .addComponent(jButton_DesignNew)
                            .addComponent(jLabel_Design))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPstudy_designLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_FileMatch)
                            .addComponent(jButton_FileMatchApply))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_DesignApply1)
                            .addComponent(jButton_DesignApply2)
                            .addComponent(jLabel_DesignLevels1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_DesignLevels2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPstudy_designLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPstudy_design, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPstudy_design, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initExpFactorsTable()
    {
        Object[] columnName = {"factor","level","file match"};          
        jTableDM_ExpFactors = new DefaultTableModel(columnName, 1);  
        
        jTable_ExpFactors.setModel(jTableDM_ExpFactors);  
    }
    
    private void initDesignErpTable()
    {
        Object[] columnName = {"name","factor1","pair1","level1","factor2","pair2","level2"};          
        jTableDM_Design = new DefaultTableModel(columnName, 1);  
        
        jTable_Design.setModel(jTableDM_Design);  
    }
    
    private void initListFileMatch()
    {
        Object[] columnName = {"twalker","tscrambled","cwalker","cscrambled"}; 
        DefaultListModel ListMD_FileMatch = new DefaultListModel();

        for (int i = 0; i < columnName.length; i++) 
        {ListMD_FileMatch.addElement(columnName[i]);}
         
        jList_FileMatch.setModel(ListMD_FileMatch); 
    }
    
    private void jButton_FileMatchApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FileMatchApplyActionPerformed
                
        Object[] obj_list_select = jList_FileMatch.getSelectedValues();
        String[] str_list_select = new String[obj_list_select.length];
        String test_chaine = new String();
        for (int i = 0; i < obj_list_select.length; i++) 
        {
            str_list_select[i] = obj_list_select[i].toString();
            test_chaine = test_chaine+obj_list_select[i].toString()+"; ";
        }

        jTableDM_ExpFactors.setValueAt(test_chaine, jTable_ExpFactors.getSelectedRow(), 2);

    }//GEN-LAST:event_jButton_FileMatchApplyActionPerformed

    private void jButton_ExpFactorsNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExpFactorsNewActionPerformed
        Object[] obj=null;
        jTableDM_ExpFactors.addRow(obj);
        jTable_ExpFactors.setModel(jTableDM_ExpFactors);
    }//GEN-LAST:event_jButton_ExpFactorsNewActionPerformed

    private void jButton_ExpFactorsRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExpFactorsRemoveActionPerformed
        jTableDM_ExpFactors.removeRow(jTable_ExpFactors.getSelectedRow());
    }//GEN-LAST:event_jButton_ExpFactorsRemoveActionPerformed

    private void jButton_DesignNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DesignNewActionPerformed
        Object[] obj=null;
        jTableDM_Design.addRow(obj);
        jTable_Design.setModel(jTableDM_Design);
    }//GEN-LAST:event_jButton_DesignNewActionPerformed

    private void jButton_DesignRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DesignRemoveActionPerformed
        jTableDM_Design.removeRow(jTable_Design.getSelectedRow());
    }//GEN-LAST:event_jButton_DesignRemoveActionPerformed

    private void jButton_DesignApply1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DesignApply1ActionPerformed
        Object[] obj_list_select = jList_DesignLevels1.getSelectedValues();
        
        if (jList_DesignLevels1.getSelectedValues() == null){}
        else
        {
        String[] str_list_select = new String[obj_list_select.length];
        String test_chaine = new String();
            for (int i = 0; i < obj_list_select.length; i++) 
            {
            str_list_select[i] = obj_list_select[i].toString();
            test_chaine = test_chaine+obj_list_select[i].toString()+"; ";
            }
        jTableDM_Design.setValueAt(test_chaine, jTable_Design.getSelectedRow(), 3);
        }
    }//GEN-LAST:event_jButton_DesignApply1ActionPerformed

    private void jButton_DesignApply2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DesignApply2ActionPerformed
        Object[] obj_list_select = jList_DesignLevels2.getSelectedValues();
        
        if (jList_DesignLevels2.getSelectedValues() == null){}
        else
        {
        String[] str_list_select = new String[obj_list_select.length];
        String test_chaine = new String();
            for (int i = 0; i < obj_list_select.length; i++) 
            {
            str_list_select[i] = obj_list_select[i].toString();
            test_chaine = test_chaine+obj_list_select[i].toString()+"; ";
            }
        jTableDM_Design.setValueAt(test_chaine, jTable_Design.getSelectedRow(), 6);
        }
    }//GEN-LAST:event_jButton_DesignApply2ActionPerformed

    private void jButton_ExpFactorsApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExpFactorsApplyActionPerformed
        Object[] columnName = new Object[jTableDM_ExpFactors.getRowCount()];
        DefaultListModel ListMD_DesignLevels = new DefaultListModel();
        for (int i = 0; i < jTableDM_ExpFactors.getRowCount(); i++) 
        {
            columnName[i] = jTable_ExpFactors.getValueAt(i, 1);
            ListMD_DesignLevels.addElement(columnName[i]);
        }
        jList_DesignLevels1.setModel(ListMD_DesignLevels); 
        jList_DesignLevels2.setModel(ListMD_DesignLevels);

        Object[] cmbinitvalues = new Object[jTableDM_ExpFactors.getRowCount()];
        for (int i = 0; i < jTableDM_ExpFactors.getRowCount(); i++) 
        {
            cmbinitvalues[i] = jTable_ExpFactors.getValueAt(i, 0);
        }
        JComboBox comboBox = new JComboBox(cmbinitvalues);
        TableCellEditor editor = new DefaultCellEditor(comboBox);        
        jTable_Design.getColumnModel().getColumn(1).setCellEditor(editor);        
        jTable_Design.getColumnModel().getColumn(4).setCellEditor(editor);
    }//GEN-LAST:event_jButton_ExpFactorsApplyActionPerformed

    DefaultTableModel jTableDM_Design;
    DefaultTableModel jTableDM_ExpFactors;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DesignApply1;
    private javax.swing.JButton jButton_DesignApply2;
    private javax.swing.JButton jButton_DesignNew;
    private javax.swing.JButton jButton_DesignRemove;
    private javax.swing.JButton jButton_ExpFactorsApply;
    private javax.swing.JButton jButton_ExpFactorsNew;
    private javax.swing.JButton jButton_ExpFactorsRemove;
    private javax.swing.JButton jButton_FileMatchApply;
    private javax.swing.JCheckBox jCheckBox_DoErp;
    private javax.swing.JCheckBox jCheckBox_DoErpim;
    private javax.swing.JCheckBox jCheckBox_DoErsp;
    private javax.swing.JCheckBox jCheckBox_DoRecompute;
    private javax.swing.JCheckBox jCheckBox_DoSpec;
    private javax.swing.JLabel jLabel_Design;
    private javax.swing.JLabel jLabel_DesignLevels1;
    private javax.swing.JLabel jLabel_DesignLevels2;
    private javax.swing.JLabel jLabel_ExpFactors;
    private javax.swing.JLabel jLabel_FileMatch;
    private javax.swing.JLabel jLabel_StudyFilename;
    private javax.swing.JList jList_DesignLevels1;
    private javax.swing.JList jList_DesignLevels2;
    private javax.swing.JList jList_FileMatch;
    private javax.swing.JPanel jPstudy_design;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable_Design;
    private javax.swing.JTable jTable_ExpFactors;
    private javax.swing.JTextField jTextField_StudyFilename;
    // End of variables declaration//GEN-END:variables
}
