/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.plaf.FileChooserUI;
import structures.Project;
       
/**
 *
 * @author goccia
 */
public class JTPMain extends javax.swing.JPanel {

    /**
     * Creates new form basePanel
     * @throws java.io.IOException
     */
    public JTPMain(){
        
        initComponents();
        initGui();

        //try{
         
        project = new Project();
        //project = project.loadMAT("C:\\Users\\PHilt\\Desktop\\behaviour_platform\\PAP\\eeg_tools_gui\\project_new_2.mat");
  
        //int verif = project.saveMAT("C:\\Users\\PHilt\\Desktop\\test_gui\\project_new_1.mat");

        /*
        }
        catch(IOException e){
            e.printStackTrace();
        }
        */
         
    }

    private void initGui()
    {
        ptask = new JPTask(this);
        main_tab.add(ptask);
        ptask.setVisible(true);        
        main_tab.setTitleAt(0, "Task");
        
        pimp = new JPImport(this);
        main_tab.add(pimp);
        pimp.setVisible(true);        
        main_tab.setTitleAt(1, "Import");
        
        ppreproc = new JPPreprocessing(this);
        main_tab.add(ppreproc);
        ppreproc.setVisible(true);        
        main_tab.setTitleAt(2, "Preprocessing");
        
        pepoching = new JPEpoching(this);
        main_tab.add(pepoching);
        pepoching.setVisible(true);        
        main_tab.setTitleAt(3, "Epoching");
        
        psubjects = new JPSubjects(this);
        main_tab.add(psubjects);
        psubjects.setVisible(true);        
        main_tab.setTitleAt(4, "Subjects");
        
        pstudy = new JPStudyDesign(this);
        main_tab.add(pstudy);
        pstudy.setVisible(true);        
        main_tab.setTitleAt(5, "Study Design");
        
        /*
        perp = new JPErp(this);
        main_tab.add(perp);
        perp.setVisible(true);        
        main_tab.setTitleAt(6, "Erp");
        
        persp = new JPErsp(this);
        main_tab.add(persp);
        persp.setVisible(true);        
        main_tab.setTitleAt(7, "Ersp");
        */
        
        pbrainstorm = new JPBrainstorm(this);
        main_tab.add(pbrainstorm);
        pbrainstorm.setVisible(true);        
        main_tab.setTitleAt(6, "Brainstorm");
        
        poperations = new JPOperations(this);
        main_tab.add(poperations);
        poperations.setVisible(true);        
        main_tab.setTitleAt(7, "Operations");
        
        ppaths = new JPPaths(this);
        main_tab.add(ppaths);
        ppaths.setVisible(true);        
        main_tab.setTitleAt(8, "Paths");
    }
    
    public void setGUI(Project proj)
    {
        project = proj; 
 
        ptask.setGUI(project); 
        pimp.setGUI(project); 
        ppreproc.setGUI(project);
        pepoching.setGUI(project);
        psubjects.setGUI(project);
        pstudy.setGUI(project);
        
        poperations.setGUI(project);
        pbrainstorm.setGUI(project);
        /*
        //perp.setGUI(project.erp);
        //persp.setGUI(project.ersp);
        ppaths.setGUI(project.paths);
        */
    }    
    
    public Project getGUI()
    {
        project.task = ptask.getGUI(); 
        project.imp = pimp.getGUI();
        project.preproc = ppreproc.getGUI(); 
        project.epoching = pepoching.getGUI(); 
        project.subjects = psubjects.getGUI(); 
        project.study = pstudy.getGUI();
        
        project.brainstorm = pbrainstorm.getGUI(); 
        project.operations = poperations.getGUI(); 
        /*  
        //project.erp = perp.getGUI(); 
        //project.ersp = persp.getGUI(); 
        project.paths = ppaths.getGUI(); 
        */
        
        return project;
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNewProject = new javax.swing.JButton();
        btOpenProject = new javax.swing.JButton();
        btSaveProject = new javax.swing.JButton();
        btSaveAsProject = new javax.swing.JButton();
        main_tab = new javax.swing.JTabbedPane();
        jLab_project_path = new javax.swing.JLabel();

        setName("main_panel"); // NOI18N

        btNewProject.setText("New");
        btNewProject.setName("btNewProject"); // NOI18N
        btNewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewProjectActionPerformed(evt);
            }
        });

        btOpenProject.setText("Open");
        btOpenProject.setName("btOpenProject"); // NOI18N
        btOpenProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenProjectActionPerformed(evt);
            }
        });

        btSaveProject.setText("Save");
        btSaveProject.setName("btSaveProject"); // NOI18N
        btSaveProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveProjectActionPerformed(evt);
            }
        });

        btSaveAsProject.setText("SaveAs");
        btSaveAsProject.setName("btSaveAsProject"); // NOI18N
        btSaveAsProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveAsProjectActionPerformed(evt);
            }
        });

        main_tab.setName("main_tab"); // NOI18N

        jLab_project_path.setText("Current file");
        jLab_project_path.setName("$project_path"); // NOI18N
        jLab_project_path.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(main_tab)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNewProject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btOpenProject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSaveProject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSaveAsProject)
                        .addGap(18, 18, 18)
                        .addComponent(jLab_project_path, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLab_project_path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btNewProject)
                        .addComponent(btOpenProject)
                        .addComponent(btSaveProject)
                        .addComponent(btSaveAsProject)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(main_tab, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btOpenProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenProjectActionPerformed
        JFileChooser fc = new JFileChooser("C:\\Users\\PHilt\\Desktop\\behaviour_platform\\PAP\\eeg_tools_gui"); 
        fc.showOpenDialog(null);
        s_project_mat_file = fc.getSelectedFile().getAbsolutePath();
        System.out.println("loading : " + s_project_mat_file);
        jLab_project_path.setText(s_project_mat_file);

        
        project.loadMAT(s_project_mat_file);
        setGUI(project);
    }//GEN-LAST:event_btOpenProjectActionPerformed

    private void btSaveProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveProjectActionPerformed
        getGUI();
        try
        {
        project.saveMAT(s_project_mat_file);
        }
        catch(IOException e){
            e.printStackTrace();
        }
        jLab_project_path.setText(s_project_mat_file);
        
    }//GEN-LAST:event_btSaveProjectActionPerformed
 
    private void btSaveAsProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveAsProjectActionPerformed
        getGUI();
        JFileChooser fc = new JFileChooser(); fc.showOpenDialog(null);
        s_project_mat_file = fc.getSelectedFile().getAbsolutePath();
        System.out.println("saving : " + s_project_mat_file);
        try
        {
        project.saveMAT(s_project_mat_file);
        }
        catch(IOException e){
            e.printStackTrace();
        }
        jLab_project_path.setText(s_project_mat_file);
    }//GEN-LAST:event_btSaveAsProjectActionPerformed

    private void btNewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewProjectActionPerformed
        //project.loadMAT(s_project_mat_file);
        //initGui();
        System.out.println("Stop do that, please");
    }//GEN-LAST:event_btNewProjectActionPerformed

    public String s_project_mat_file;
    public Project project;
    
    private JTPMain pmain;
    private JPTask ptask;
    private JPImport pimp;
    private JPPreprocessing ppreproc;
    private JPEpoching pepoching;
    private JPSubjects psubjects;
    private JPStudyDesign pstudy;
    private JPErp perp;
    private JPErsp persp;
    private JPBrainstorm pbrainstorm;
    private JPOperations poperations;
    private JPPaths ppaths;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNewProject;
    private javax.swing.JButton btOpenProject;
    private javax.swing.JButton btSaveAsProject;
    private javax.swing.JButton btSaveProject;
    private javax.swing.JLabel jLab_project_path;
    private javax.swing.JTabbedPane main_tab;
    // End of variables declaration//GEN-END:variables
}
