/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import structures.Epoching;
import structures.Project;
import structures.Task;

/**
 *
 * @author alba
 */
public class JPEpoching extends javax.swing.JPanel {

    private JTPMain controller;
    public Epoching epoching;
    public Project project;
    
    
    public JPEpoching(JTPMain ctrl) {
        initComponents();
        controller = ctrl;
    }
    
    public void setGUI(Project proj)
    {
        project = proj;
        epoching = project.epoching;
        
        initConditionTriggersTable();
    }
    
    public Project getGUI(Project proj)
    {
        proj.epoching.baseline_replace.mode                         = (String) jComboBox_BaselineReplaceMode.getSelectedItem();
        proj.epoching.baseline_replace.baseline_originalposition    = (String) jComboBox_BaselineReplaceOriginalPos.getSelectedItem();
        proj.epoching.baseline_replace.baseline_finalposition       = (String) jComboBox_BaselineReplaceFinalPos.getSelectedItem();
        proj.epoching.baseline_replace.replace                      = (String) jComboBox_BaselineReplaceReplace.getSelectedItem();

        return proj;
    }
    
    private void initConditionTriggersTable()
    {
        Object[] columnName = {"Name","Triggers codes"};       
        int l_mrkcode = project.epoching.mrkcode_cond.length;
        jTableDM_ConditionTriggers = new DefaultTableModel(columnName, l_mrkcode);
        jTable_ConditionTriggers.setModel(jTableDM_ConditionTriggers);        
        
        for (int i = 0; i < project.epoching.mrkcode_cond.length; i++) 
        {
            String str_mrkcode = new String("");
            for (int j = 0; j < project.epoching.mrkcode_cond[0].length; j++) 
            {
                str_mrkcode = str_mrkcode + "," + project.epoching.mrkcode_cond[i][j];
            }
            jTable_ConditionTriggers.setValueAt("str_mrkcode", i, 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPepoching = new javax.swing.JPanel();
        jLabel_BaselineReplaceMode = new javax.swing.JLabel();
        jComboBox_BaselineReplaceMode = new javax.swing.JComboBox();
        jLabel_BaselineReplace = new javax.swing.JLabel();
        jLabel_BaselineReplaceOriginalPos = new javax.swing.JLabel();
        jComboBox_BaselineReplaceOriginalPos = new javax.swing.JComboBox();
        jLabel_BaselineReplaceFinalPos = new javax.swing.JLabel();
        jComboBox_BaselineReplaceFinalPos = new javax.swing.JComboBox();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable_ConditionTriggers = new javax.swing.JTable();
        jLabel_Conditions = new javax.swing.JLabel();
        jLabel_BaselineReplaceReplace = new javax.swing.JLabel();
        jComboBox_BaselineReplaceReplace = new javax.swing.JComboBox();

        jPepoching.setName("epoching"); // NOI18N

        jLabel_BaselineReplaceMode.setText("mode");

        jComboBox_BaselineReplaceMode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_BaselineReplaceMode.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox_BaselineReplaceMode.setName(""); // NOI18N

        jLabel_BaselineReplace.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_BaselineReplace.setText("Baseline Replace");

        jLabel_BaselineReplaceOriginalPos.setText("original position");

        jComboBox_BaselineReplaceOriginalPos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel_BaselineReplaceFinalPos.setText("final position");

        jComboBox_BaselineReplaceFinalPos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable_ConditionTriggers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "triggers codes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_ConditionTriggers.getTableHeader().setReorderingAllowed(false);
        jScrollPane10.setViewportView(jTable_ConditionTriggers);

        jLabel_Conditions.setText("CONDITIONS");

        jLabel_BaselineReplaceReplace.setText("replace");

        jComboBox_BaselineReplaceReplace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPepochingLayout = new javax.swing.GroupLayout(jPepoching);
        jPepoching.setLayout(jPepochingLayout);
        jPepochingLayout.setHorizontalGroup(
            jPepochingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPepochingLayout.createSequentialGroup()
                .addGroup(jPepochingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPepochingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPepochingLayout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(jLabel_BaselineReplaceMode, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBox_BaselineReplaceMode, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(jLabel_BaselineReplaceOriginalPos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox_BaselineReplaceOriginalPos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel_BaselineReplaceFinalPos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox_BaselineReplaceFinalPos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(jLabel_BaselineReplaceReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox_BaselineReplaceReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPepochingLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel_BaselineReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPepochingLayout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(jLabel_Conditions, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPepochingLayout.setVerticalGroup(
            jPepochingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPepochingLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel_BaselineReplace)
                .addGap(18, 18, 18)
                .addGroup(jPepochingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPepochingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_BaselineReplaceReplace)
                        .addComponent(jComboBox_BaselineReplaceReplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPepochingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_BaselineReplaceFinalPos)
                        .addComponent(jComboBox_BaselineReplaceFinalPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPepochingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_BaselineReplaceOriginalPos)
                        .addComponent(jComboBox_BaselineReplaceOriginalPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPepochingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_BaselineReplaceMode)
                        .addComponent(jComboBox_BaselineReplaceMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addComponent(jLabel_Conditions)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPepoching, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPepoching, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel jTableDM_ConditionTriggers;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox_BaselineReplaceFinalPos;
    private javax.swing.JComboBox jComboBox_BaselineReplaceMode;
    private javax.swing.JComboBox jComboBox_BaselineReplaceOriginalPos;
    private javax.swing.JComboBox jComboBox_BaselineReplaceReplace;
    private javax.swing.JLabel jLabel_BaselineReplace;
    private javax.swing.JLabel jLabel_BaselineReplaceFinalPos;
    private javax.swing.JLabel jLabel_BaselineReplaceMode;
    private javax.swing.JLabel jLabel_BaselineReplaceOriginalPos;
    private javax.swing.JLabel jLabel_BaselineReplaceReplace;
    private javax.swing.JLabel jLabel_Conditions;
    private javax.swing.JPanel jPepoching;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JTable jTable_ConditionTriggers;
    // End of variables declaration//GEN-END:variables
}
