% function to play a movie and - if required - a sound at a given frame of the video.
% function movie_sound(MOVIE,SOUND, SOUND_FRAME, WIN, DIO, TEST,DURATION ) where
% MOVIE is the full path of the video (possible future modifications could include animation from pshycotoolbox)
% SOUND is the full path of the sound (possible future modifications could include sound directly generated by matlab)
% SOUND_FRAME is the frame of the movie when the SOUND starts
% WIN is the window where the MOVIE is played
% DIO is an object mapping a parallel port. it has to be previously created by dio=dio=digitalio('parallel','PARALLEL_NAME') and initialized by line=addline(dio,0:m,'out'); where m is the number of trigger types - 1
% TEST is the choice between send and not-send trigger to the paralle port: TEST=0 run in test mode and DOES NOT send the trigger.


function movie_sound(movie,sound, sound_frame, win, dio, test,duration )

white = [255 255 255];
black = [0 0 0];

try

    % Open movie file:
    movie = Screen('OpenMovie', win, moviename);

    % Start playback engine:
    Screen('PlayMovie', movie, 1);

    frame_counter=0;
    send_trigger = 0;
    
    for j = 1:90
        tex(j) = Screen('GetMovieImage', win, movie);
    end
    % Playback loop: Runs until end of movie or keypress:
    while 1
        % Wait for next movie frame, retrieve texture handle to it
        %tex = Screen('GetMovieImage', win, movie);

        % Valid texture returned? A negative value means end of movie reached:
        frame_counter = frame_counter+1
        
        if tex(frame_counter) <0
            % We're done, break out of loop:
            break
        end

        % Draw the new texture immediately to screen:
        Screen('DrawTexture', win, tex(frame_counter));

        switch frame_counter
            %case 1
             %    putvalue(port, 1);
            %case 2
            %     putvalue(port, 0);
%             case 41
%                  Screen('FillRect', win, white, [0,0,100,100]);
%                  putvalue(port, 1);                
%             case 42
%                  putvalue(port, 0);
%             case 43
%                  Screen('FillRect', win, white, [0,0,100,100]);
%                  putvalue(port, 1);                
             case 40
                  trigger(ao);
            case 45                 
                 Screen('FillRect', win, white, [0,0,100,100]);
                 send_trigger = 1;       
                 
            case 46
                Screen('FillRect', win, black, [0,0,100,100]);
                 putvalue(port, 0);
                 send_trigger = 0;              
        end    

        % Update display:
        Screen('Flip', win);  
        if send_trigger
            putvalue(port, 1); 
        end
        % Release texture:
        Screen('Close', tex(frame_counter));
    end 


end